-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.cart_has_products (
    cart_id integer NOT NULL,
    product_id integer NOT NULL,
    qty integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.carts (
    cart_id integer NOT NULL GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    user_id integer NOT NULL REFERENCES users(user_id),
    created date NOT NULL,
    modified date NOT NULL,
    CONSTRAINT carts_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.categories (
    category_id integer NOT NULL GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.order_has_products (
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    qty integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.orders (
    order_id integer NOT NULL GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    user_id integer NOT NULL,
    date date NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.products (
    product_id integer NOT NULL GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    category_id integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    price numeric(5, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions (
    sid character varying COLLATE pg_catalog."default" NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (sid)
);

CREATE TABLE IF NOT EXISTS public.users (
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    fname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    lname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(70) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    password text COLLATE pg_catalog."default" NOT NULL,
    isAdmin boolean NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE
    IF EXISTS public.cart_has_products
ADD
    CONSTRAINT cart_has_products_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts (cart_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.cart_has_products
ADD
    CONSTRAINT cart_has_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (product_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.order_has_products
ADD
    CONSTRAINT order_has_products_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (order_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.order_has_products
ADD
    CONSTRAINT order_has_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (product_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.orders
ADD
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.products
ADD
    CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories (category_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE
    IF EXISTS public.users
ADD
    CONSTRAINT users_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts (cart_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

END;